version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=insanefoam
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=webchat

  scylla-node-root:
    image: scylladb/scylla:latest
    networks:
      - scylla
    ports:
      - '9042:9042'

  elastic:
    image: elasticsearch:8.1.3
    networks:
      - elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node

networks:
  scylla:
    driver: bridge
  elastic:
    driver: bridge
